name: codelandia_to_do_riverpod
description: To Do App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.1
  font_awesome_flutter: ^10.5.0
  uuid: ^3.0.7
  intl: ^0.18.1
  animations: ^2.0.8
  alarm: ^2.0.0
  flutter_svg: ^2.0.7
  hive_flutter: ^1.1.0
  flutter_slidable: ^3.0.0
  easy_localization: ^3.0.3
  fl_chart: ^0.63.0
  lottie: ^2.6.0
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  quick_actions: ^1.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3


flutter:

  uses-material-design: true

  assets:
    - assets/alarms/
    - assets/images/
    - assets/translations/
    - assets/lotties/

